<div>
    <p>
        Tohle je vygenerovanej lokalizovanej link, kdyz se z configu odebere hodnota remoteLangFrom = 'uri' odebere se z linku informace o langu.<br />
        WebRoot se tam taktez dodava autoaticky.<br />
        Link se generuje pomoci staticke metody build tridy Link<br />
        <b>Link::<i>build</i>('content/show/45');</b> =>
        <?php echo $this->data ?>
    </p>
</div>
<div>Tak toto je strasne generovane modulem content.</div>