<body>
<div id="wrapper">
	<div id="header">
        <?php echo $this->getContainer('header'); ?>
        
		<h1><?php echo $this->title ?></h1>

		<h2><a href="http://www.freecsstemplates.org">By Free CSS Templates</a></h2>
		<ul>
			<li class="first"><a href="/" accesskey="1" title="">Home</a></li>
			<li><a href="/bobradmin/" accesskey="2" title="">Administrace</a></li>
            <li><a href="<?php echo Lib_Link::build('login/login') ?> " accesskey="3" title="">Login</a></li>
		</ul>
	</div>
</div>
<div id="content">
	<div id="colOne">
        <?php
        echo Lib_Messanger::flush();
        echo $this->getContainer('center');
        ?>
	</div>
	<div id="colTwo">
        <?php echo $this->getContainer('right') ?>
	</div>
</div>
<div id="footer">
	<p><?php echo $this->getContainer('footer') ?> Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
</body>